name: Codacy Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Build and test with coverage
      run: mvn clean test -Dtest='**/modelo/*Test,**/indicadores/*Test,**/grafico/*Test'

    - name: Generate coverage report
      run: |
        echo "Coverage report generated at target/site/jacoco/jacoco.xml"
        ls -la target/site/jacoco/ || echo "No coverage report found"