name: DeepSource Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  deepsource:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Build and test with coverage
      run: mvn clean test -Dtest='**/modelo/*Test,**/indicadores/*Test,**/grafico/*Test,**/utils/*Test'

    - name: Report results to DeepSource
      run: |
        if [ -n "${{ secrets.DEEPSOURCE_DSN }}" ]; then
          curl https://deepsource.io/cli | sh
          ./bin/deepsource report --analyzer test-coverage --key java --value-file target/site/jacoco/jacoco.xml || echo "DeepSource upload failed - check analyzer configuration"
        else
          echo "DEEPSOURCE_DSN not configured - skipping upload"
        fi
      env:
        DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}